# Generated by Django 3.0.3 on 2020-03-13 13:01

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import jsonfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('Authentication', '0005_auto_20200313_1401'),
        ('spotify', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SpotifyUser',
            fields=[
                ('username', models.CharField(default='', max_length=250, primary_key=True, serialize=False)),
                ('last_updated', models.DateField(blank=True, default=django.utils.timezone.now)),
                ('artist_count', jsonfield.fields.JSONField(blank=True, default=None)),
                ('genre_count', jsonfield.fields.JSONField(blank=True, default=None)),
                ('extended_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Authentication.ExtendedUser')),
                ('songs', models.ManyToManyField(blank=True, to='spotify.Song')),
            ],
        ),
    ]
