# Generated by Django 3.0.3 on 2020-03-17 19:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('spotify', '0002_spotifyuser'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='spotifyuser',
            name='extended_user',
        ),
    ]
