# Generated by Django 3.0.4 on 2020-04-05 10:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import jsonfield.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0011_update_proxy_permissions'),
    ]

    operations = [
        migrations.CreateModel(
            name='Artist',
            fields=[
                ('id', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('name', models.CharField(max_length=100, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Song',
            fields=[
                ('id', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('artists', models.ManyToManyField(to='main.Artist')),
            ],
        ),
        migrations.CreateModel(
            name='SpotifyUser',
            fields=[
                ('username', models.CharField(default='', max_length=250, primary_key=True, serialize=False)),
                ('last_updated', models.DateField(default=None, null=True)),
                ('artist_count', jsonfield.fields.JSONField(default=None, null=True)),
                ('genre_count', jsonfield.fields.JSONField(default=None, null=True)),
                ('songs', models.ManyToManyField(blank=True, to='main.Song')),
            ],
        ),
        migrations.CreateModel(
            name='ExtendedUser',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('access_token', models.CharField(blank=True, max_length=250)),
                ('refresh_token', models.CharField(blank=True, max_length=250)),
                ('spotify_account', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.SpotifyUser')),
            ],
        ),
        migrations.AddField(
            model_name='artist',
            name='genres',
            field=models.ManyToManyField(to='main.Genre'),
        ),
    ]
