# Generated by Django 2.2.7 on 2019-12-09 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Authentication', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofile',
            old_name='spotify_id',
            new_name='token',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='spotify_username',
            field=models.CharField(default='', max_length=64),
            preserve_default=False,
        ),
    ]
