# Generated by Django 3.0.3 on 2020-02-29 17:01

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('Authentication', '0002_auto_20200220_1701'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='last_updated',
            field=models.DateField(blank=True, default=django.utils.timezone.now),
        ),
    ]
