# Generated by Django 2.2.7 on 2019-12-10 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Authentication', '0002_auto_20191209_2005'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='spotify_username',
            field=models.CharField(default='', max_length=64),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='token',
            field=models.CharField(blank=True, max_length=250),
        ),
    ]
