# Generated by Django 2.2.7 on 2019-12-10 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Authentication', '0003_auto_20191210_1103'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofile',
            old_name='token',
            new_name='access_token',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='refresh_token',
            field=models.CharField(blank=True, max_length=250),
        ),
    ]
