# Generated by Django 3.0.3 on 2020-03-02 16:14

from django.db import migrations
import jsonfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('Authentication', '0003_userprofile_last_updated'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='artist_count',
            field=jsonfield.fields.JSONField(blank=True, default=None),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='genre_count',
            field=jsonfield.fields.JSONField(blank=True, default=None),
        ),
    ]
