# Generated by Django 3.0.3 on 2020-03-13 13:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0011_update_proxy_permissions'),
        ('Authentication', '0004_auto_20200302_1714'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExtendedUser',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('access_token', models.CharField(blank=True, max_length=250)),
                ('refresh_token', models.CharField(blank=True, max_length=250)),
            ],
        ),
        migrations.DeleteModel(
            name='UserProfile',
        ),
    ]
