# Generated by Django 2.2.7 on 2019-12-11 11:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Authentication', '0004_auto_20191210_1330'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='spotify_username',
        ),
    ]
