# Generated by Django 3.0.3 on 2020-02-15 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spotify', '0001_initial'),
        ('Authentication', '0005_remove_userprofile_spotify_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='songs',
            field=models.ManyToManyField(to='spotify.Song'),
        ),
    ]
