# Generated by Django 3.0.3 on 2020-03-17 19:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('spotify', '0003_remove_spotifyuser_extended_user'),
        ('Authentication', '0005_auto_20200313_1401'),
    ]

    operations = [
        migrations.AddField(
            model_name='extendeduser',
            name='spotify_account',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='spotify.SpotifyUser'),
        ),
    ]
